### ISSUE TITLE
High / Low prio mobs not changing color with style filter

### ISSUE THREAD

**Issue by XaVion89** [mBlinkii/MaUI-ElvUI-Profile-Strings#23]
Hello Blinkiii,

thank you for providing an awesome UI. Ive decided to only use your coloring for m+ scenarios and I've a question.
It seems that only the stunnable and interuptable mobs are colored. The other ones do not change the color, even though i installed the filters correctly. 

I've attached a screenshot for visualzing purposes.

Do you have any idea what I've done wrong? 

![Screenshot 2024-11-17 115656](https://github.com/user-attachments/assets/dc00f011-5066-43f8-a45a-70ca32eff860)

**Comment by mBlinkii** [comment]
Hi, you will not see all filters outside the combat. Only the filters Prio 1 - 3 have an additional filter that shows them outside the combat. the other filters will only be visible in the battle if your threat is good. 
This has been done so that I as a tank can see whether my threat is good or bad, otherwise, it would not be possible if the filters overwrite the threat colors.
